
services:
  # PostgreSQL Database for Kong
  kong-database:
    image: postgres:11 # Downgrade to PostgreSQL 11 for compatibility
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-database-data:/var/lib/postgresql/data
    networks:
      - kong-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong -d kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kong Gateway Service
  kong:
    image: kong/kong-gateway:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_PORTAL: "off" # Optional: Disable Kong portal if not needed
    depends_on:
      kong-database:
        condition: service_healthy
    ports:
      - '8000:8000' # Kong Proxy
      - '8443:8443' # Kong Proxy SSL
      - '8001:8001' # Kong Admin API
      - '8444:8444' # Kong Admin API SSL
    networks:
      - kong-net
    volumes:
      - kong-data:/usr/local/kong
    command: |
      /bin/sh -c "
        chown -R kong:kong /usr/local/kong &&
        kong migrations bootstrap &&
        kong start
      "

  # Konga UI for Kong Gateway Management
  konga:
    image: pantsel/konga:latest
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_USER: kong
      DB_PASSWORD: kong
      DB_DATABASE: kong
    depends_on:
      kong-database:
        condition: service_healthy
    ports:
      - '1337:1337' # Konga UI
    networks:
      - kong-net

volumes:
  kong-database-data: # Persistent storage for PostgreSQL
  kong-data:          # Persistent storage for Kong Gateway configurations

networks:
  kong-net:
    driver: bridge
